export const theme = {
  name: 'Haute Horlogerie Atelier',
  colors: {
    surface: '#fcf9f8',
    surfaceDim: '#dcd9d9',
    surfaceBright: '#fcf9f8',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f6f3f2',
    surfaceContainer: '#f0edec',
    surfaceContainerHigh: '#ebe7e7',
    surfaceContainerHighest: '#e5e2e1',
    onSurface: '#1c1b1b',
    onSurfaceVariant: '#4e4639',
    inverseSurface: '#313030',
    inverseOnSurface: '#f3f0ef',
    outline: '#7f7667',
    outlineVariant: '#d1c5b4',
    surfaceTint: '#775a19',
    primary: '#775a19',
    onPrimary: '#ffffff',
    primaryContainer: '#c5a059',
    onPrimaryContainer: '#4e3700',
    inversePrimary: '#e9c176',
    secondary: '#5f5e5e',
    onSecondary: '#ffffff',
    secondaryContainer: '#e5e2e1',
    onSecondaryContainer: '#656464',
    tertiary: '#665d55',
    onTertiary: '#ffffff',
    tertiaryContainer: '#aea39a',
    onTertiaryContainer: '#413933',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    primaryFixed: '#ffdea5',
    primaryFixedDim: '#e9c176',
    onPrimaryFixed: '#261900',
    onPrimaryFixedVariant: '#5d4201',
    secondaryFixed: '#e5e2e1',
    secondaryFixedDim: '#c9c6c5',
    onSecondaryFixed: '#1c1b1b',
    onSecondaryFixedVariant: '#474646',
    tertiaryFixed: '#ede0d7',
    tertiaryFixedDim: '#d0c4bb',
    onTertiaryFixed: '#201a15',
    onTertiaryFixedVariant: '#4d453f',
    background: '#fcf9f8',
    onBackground: '#1c1b1b',
    surfaceVariant: '#e5e2e1',
    // Brand Palette Narrative Aliases
    champagneGold: '#C5A059',
    obsidian: '#0A0A0A',
    titanium: '#8C827A',
    carbonBlack: '#121212',
    alabaster: '#F9F9F8',
    opticWhite: '#FFFFFF',
    hairline: '#E5E5E3',
    hairlineDark: '#2A2A28',
    goldGlow: 'rgba(197, 160, 89, 0.4)',
  },
  typography: {
    displayHero: {
      fontFamily: 'Bodoni Moda',
      fontSize: '4.5rem',
      fontWeight: '400',
      lineHeight: '5rem',
      letterSpacing: '0.08em',
    },
    displayHeroMobile: {
      fontFamily: 'Bodoni Moda',
      fontSize: '2.5rem',
      fontWeight: '400',
      lineHeight: '3rem',
      letterSpacing: '0.06em',
    },
    headlineXl: {
      fontFamily: 'Bodoni Moda',
      fontSize: '3rem',
      fontWeight: '400',
      lineHeight: '3.5rem',
      letterSpacing: '0.05em',
    },
    headlineXlMobile: {
      fontFamily: 'Bodoni Moda',
      fontSize: '2rem',
      fontWeight: '400',
      lineHeight: '2.5rem',
      letterSpacing: '0.04em',
    },
    headlineLg: {
      fontFamily: 'Bodoni Moda',
      fontSize: '2rem',
      fontWeight: '500',
      lineHeight: '2.5rem',
      letterSpacing: '0.04em',
    },
    headlineMd: {
      fontFamily: 'Bodoni Moda',
      fontSize: '1.5rem',
      fontWeight: '500',
      lineHeight: '2rem',
      letterSpacing: '0.03em',
    },
    titleSm: {
      fontFamily: 'Hanken Grotesk',
      fontSize: '1.125rem',
      fontWeight: '500',
      lineHeight: '1.625rem',
      letterSpacing: '0.02em',
    },
    bodyLg: {
      fontFamily: 'Hanken Grotesk',
      fontSize: '1.125rem',
      fontWeight: '400',
      lineHeight: '1.875rem',
      letterSpacing: '0.01em',
    },
    bodyMd: {
      fontFamily: 'Hanken Grotesk',
      fontSize: '0.9375rem',
      fontWeight: '400',
      lineHeight: '1.625rem',
      letterSpacing: '0.01em',
    },
    bodySm: {
      fontFamily: 'Hanken Grotesk',
      fontSize: '0.8125rem',
      fontWeight: '400',
      lineHeight: '1.375rem',
      letterSpacing: '0.02em',
    },
    labelUppercase: {
      fontFamily: 'Hanken Grotesk',
      fontSize: '0.6875rem',
      fontWeight: '600',
      lineHeight: '1rem',
      letterSpacing: '0.22em',
      textTransform: 'uppercase' as const,
    },
    technicalData: {
      fontFamily: 'Hanken Grotesk',
      fontSize: '0.75rem',
      fontWeight: '500',
      lineHeight: '1.125rem',
      letterSpacing: '0.14em',
      textTransform: 'uppercase' as const,
    },
  },
  spacing: {
    gutter: '1.5rem',
    gutterDesktop: '2.5rem',
    margin: '1.5rem',
    marginTablet: '3rem',
    marginDesktop: '5rem',
    spaceXs: '0.25rem',
    spaceSm: '0.5rem',
    spaceMd: '1rem',
    spaceLg: '2rem',
    spaceXl: '4rem',
    space2xl: '7rem',
  },
  borderRadius: '0px',
} as const;

export type Theme = typeof theme;
